from pathlib import Path
path = Path('BackWeb/pom.xml')
text = path.read_text()
print('START OK')
start = text.index('            <!--引入langchain4j依赖管理清单-->')
print('start', start)
end = text.index('\n        </dependencies>', start)
print('end', end)
path.write_text(text[:start] + '\n' + text[end:])
print('done')
